apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - name: conversor
        image: vguimaraes/conversao-temperatura:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: conversor
spec:
  selector:
    app: conversor
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
